CREATE DATABASE NOVELLA

CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    AUTHOR VARCHAR(50) NOT NULL,
    PRICE MONEY NOT NULL,
    STOCK INT NOT NULL,
    BOOK_DESCRIPTION VARCHAR(255),
    IMAGE_URL VARCHAR(100)
);

CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(50) NOT NULL,
    ROLE VARCHAR(5) NOT NULL
);

CREATE TABLE CART (
   CART_ID INT PRIMARY KEY NOT NULL,
   USER_ID INT NOT NULL,
   BOOK_ID INT NOT NULL,
   QUANTITY INT NOT NULL

   FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
   FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

CREATE TABLE ORDERS (
   ORDER_ID INT PRIMARY KEY NOT NULL,
   USER_ID INT NOT NULL,
   TOTAL_PRICE MONEY NOT NULL,
   STATUS VARCHAR(15) NOT NULL,
   CREATED_AT DATE NOT NULL
);

CREATE TABLE ORDER_ITEMS (
   ORDER_ITEMS_ID INT PRIMARY KEY NOT NULL,
   ORDER_ID INT NOT NULL,
   BOOK_ID INT NOT NULL,
   QUANTITY INT NOT NULL,
   PRICE MONEY NOT NULL

   FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
   FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);


